import os

lines = []
a = lines.append
a('package com.devwithguru.cricket.ui.feature.tournament')
a('')
a('import androidx.lifecycle.SavedStateHandle')
a('import androidx.lifecycle.ViewModel')
a('import androidx.lifecycle.viewModelScope')
a('import com.devwithguru.cricket.data.api.DraftPickData')
a('import com.devwithguru.cricket.data.api.DraftRoundData')
a('import com.devwithguru.cricket.data.api.CreateFixtureRequest')
a('import com.devwithguru.cricket.data.api.DraftSetupRequest')
a('import com.devwithguru.cricket.data.api.AdminTeamData')
a('import com.devwithguru.cricket.data.api.AdminCaptainData')
a('import com.devwithguru.cricket.data.api.AdminCaptainUser')
a('import com.devwithguru.cricket.data.api.AdminPlayerData')
a('import com.devwithguru.cricket.data.api.AdminPlayerProfile')
a('import com.devwithguru.cricket.data.db.entity.AdminTeamEntity')
a('import com.devwithguru.cricket.data.db.entity.AdminPlayerEntity')
a('import com.devwithguru.cricket.data.db.entity.AdminFixtureEntity')
a('import com.devwithguru.cricket.data.repository.AdminLocalRepository')
a('import com.devwithguru.cricket.data.repository.AuthRepository')
a('import com.devwithguru.cricket.data.repository.TournamentAdminRepository')
a('import com.devwithguru.cricket.data.repository.DraftRepository')
a('import com.devwithguru.cricket.data.sync.ConnectivityMonitor')
a('import com.google.gson.Gson')
a('import dagger.hilt.android.lifecycle.HiltViewModel')
a('import kotlinx.coroutines.flow.MutableStateFlow')
a('import kotlinx.coroutines.flow.StateFlow')
a('import kotlinx.coroutines.launch')
a('import javax.inject.Inject')